from tree import *
from binary_tree import *

root=tree(1000)
x=tree(2000)
y=tree(3000)
z=tree(4000)
x1=tree(201)
x2=tree(202)
x3=tree(203)
y1=tree(301)
y2=tree(302)
y3=tree(303)
root.AddSuccessor(x)
root.AddSuccessor(y)
root.AddSuccessor(z)
x.AddSuccessor(x1)
x.AddSuccessor(x2)
x.AddSuccessor(x3)
y.AddSuccessor(y1)
y.AddSuccessor(y2)
y.AddSuccessor(y3)
c=tree(3)
d=tree(1)
e=tree(4)
f=tree(1)
g=tree(5)
f.AddSuccessor(g)
e.AddSuccessor(f)
d.AddSuccessor(e)
c.AddSuccessor(d)
z.AddSuccessor(c)
root.Print_DepthFirst()
print(root.Get_LevelOrder(),"\n")

BT=root.ConvertToBinaryTree()
BT.Print_DepthFirst()
print(BT.Get_LevelOrder(),"\n")
G=BT.ConvertToTree()
G[1].Print_DepthFirst()
print(root.Get_LevelOrder(),"\n")
