from graph import *

x = graph()
x.addVertex(7)
x.addEdge(0,1,True,1)
x.addEdge(2,1,True,1)
x.addEdge(1,3,True,1)
x.addEdge(3,4,False,2)
x.addEdge(4,2,False,2)
#x.addEdge(4,5,True,1)
x.addEdge(5,6,False,1)
print(x.v,x.e,x.w)
print("Depth")
print(x.traverse(0,False))
print("Breadth")
print(x.traverse(0,True))
print("Breadth; start=None")
print(x.traverse(None,True))
print("Depth; start=None")
print(x.traverse(None,False))
print("Connectivity between 0 and 3")
print(x.connectivity(0,3))
print("Path between 0 and 3")
print(x.path(0,3))
